<?php// material.phprequire_once 'api/db.php';$slug = isset($_GET['slug']) ? $_GET['slug'] : '';if (empty($slug)) {    header("HTTP/1.0 404 Not Found");    echo "<h1>404 Not Found</h1>";    exit;}// Check if slug column exists$slug_exists = false;$colRes = $conn->query("SHOW COLUMNS FROM materials LIKE 'slug'");if ($colRes && $colRes->num_rows > 0) {    $slug_exists = true;}$fallback_id = 0;if (is_numeric($slug)) {    $fallback_id = (int)$slug;}if ($slug_exists) {    $stmt = $conn->prepare("SELECT * FROM materials WHERE slug = ? OR id = ?");    $stmt->bind_param("si", $slug, $fallback_id);    $stmt->execute();    $res = $stmt->get_result();} else {    // Fallback if slug column doesn't exist yet    $allRes = $conn->query("SELECT * FROM materials");    $foundId = 0;    while($row = $allRes->fetch_assoc()) {        $gen = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $row['name'] ?? '')));        $gen = preg_replace('/-+/', '-', $gen);        $gen = trim($gen, '-') ?: $row['id'];        if ($gen === $slug || (string)$row['id'] === $slug || $row['id'] == $fallback_id) {            $foundId = $row['id'];            break;        }    }    if ($foundId > 0) {        $stmt = $conn->prepare("SELECT * FROM materials WHERE id = ?");        $stmt->bind_param("i", $foundId);        $stmt->execute();        $res = $stmt->get_result();    } else {        $res = $conn->query("SELECT * FROM materials WHERE id = 0");    }}if ($res->num_rows === 0) {    header("HTTP/1.0 404 Not Found");    echo "<h1>404 Not Found - Material does not exist.</h1>";    exit;}$material = $res->fetch_assoc();$title = htmlspecialchars($material['name'] ?? 'Material') . " - Free Degree Library";$description = "Download " . htmlspecialchars($material['name'] ?? 'this material') . " uploaded by " . htmlspecialchars($material['uploader'] ?? 'User') . ". Category: " . htmlspecialchars($material['category'] ?? 'General');$canonicalUrl = "https://degreelibrary.gt.tc/material/" . htmlspecialchars($slug ?? '');$downloadUrl = "/api/download.php?id=" . $material['id'];?><!DOCTYPE html><html lang="en"><head>  <script async src="https://www.googletagmanager.com/gtag/js?id=G-VHYRJJZX5H"></script>  <script>    window.dataLayer = window.dataLayer || [];    function gtag() { dataLayer.push(arguments); }    gtag('js', new Date());    gtag('config', 'G-VHYRJJZX5H');  </script>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>Study Material - Free Degree Library</title>
  <meta name="description" content="View and download detailed study materials and academic resources for your courses.">
  <meta name="keywords" content="study resource, academic material, download notes">
  <meta name="author" content="Cirravo Solutions">
  <link rel="canonical" href="https://degreelibrary.gt.tc/material.php">
  
  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://degreelibrary.gt.tc/material.php">
  <meta property="og:title" content="Study Material - Free Degree Library">
  <meta property="og:description" content="View and download detailed study materials and academic resources for your courses.">
  <meta property="og:image" content="/logo.png">
  
  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="https://degreelibrary.gt.tc/material.php">
  <meta name="twitter:title" content="Study Material - Free Degree Library">
  <meta name="twitter:description" content="View and download detailed study materials and academic resources for your courses.">
  <meta name="twitter:image" content="/logo.png">
  
  <!-- JSON-LD Structured Data -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "Study Material - Free Degree Library",
    "description": "View and download detailed study materials and academic resources for your courses.",
    "url": "https://degreelibrary.gt.tc/material.php"
  }
  </script>  <link rel="icon" type="image/png" href="/favicon.png">  <link rel="stylesheet" href="/style.css?v=2.0.35">  <script>    window.INITIAL_ROUTE = ''; // To prevent overriding by JS if not intended  </script></head><body>  <header>    <div class="header-container">      <div class="header-left">        <div style="display: flex; flex-direction: column;">          <a href="/" class="brand">Free Degree Library</a>          <div class="brand-subtitle">Powered by: <a href="https://cirravosolutions.co.in/" target="_blank"              rel="noopener noreferrer">Cirravo Solutions</a></div>        </div>      </div>      <nav>        <a href="/">Home</a>        <a href="/upload.html">Upload</a>        <a href="/community.html">Community<span class="blinking-dot"></span></a>        <a href="/mca.html">MCA</a>        <a href="#" onclick="openSubscribeModal(event)" class="subscribe-btn">Subscribe <span            class="subscribe-count">0</span></a>        </nav>    </div>  </header>  <div id="marqueeContainer"></div>  <main style="max-width: 800px; margin: 40px auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">    <h1 style="font-size: 24px; color: #1E293B; margin-bottom: 10px;"><?php echo htmlspecialchars($material['name']); ?></h1>    <div style="margin-bottom: 20px; color: #475569; font-size: 14px;">      <p><strong>Uploader:</strong> <?php echo htmlspecialchars($material['uploader']); ?></p>      <p><strong>Category:</strong> <?php echo htmlspecialchars($material['category']); ?></p>      <p><strong>Tags:</strong> <?php echo htmlspecialchars($material['tags']); ?></p>      <p><strong>Uploaded On:</strong> <?php echo date('d/m/Y', strtotime($material['created_at'])); ?></p>    </div>    <div style="margin-top: 30px;">      <a href="<?php echo htmlspecialchars($material['file_path']); ?>" download="<?php echo htmlspecialchars($material['file_name']); ?>" onclick="event.preventDefault(); downloadFile('<?php echo $material['id']; ?>', '<?php echo htmlspecialchars($material['file_name']); ?>')" style="display: inline-block; padding: 10px 20px; background-color: #4F46E5; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;">Download Material</a>      <button onclick="shareContent('<?php echo addslashes(htmlspecialchars($material['name'])); ?>', 'Check out this study material on Free Degree Library', '/material/<?php echo htmlspecialchars($slug); ?>')" style="display: inline-block; padding: 10px 20px; background-color: #E2E8F0; color: #1E293B; text-decoration: none; border-radius: 4px; font-weight: bold; border: none; cursor: pointer; margin-left: 10px;">Share</button>    </div>    <div style="margin-top: 40px;">        <a href="/" style="color: #4F46E5; text-decoration: underline;">&larr; Back to Search</a>    </div>  </main>  <!-- We reuse the app.js for download ad logic and sidebar -->  <script src="/app.js?v=2.0.35"></script></body></html>